- hosts: all
  become: true

  roles:
    - role: gantsign.golang
    - role: geerlingguy.docker
    - role: darkwizard242.awscli

  tasks:
    - import_tasks: shell/main.yml
    - import_tasks: terraform/main.yml